### ISSUE TITLE
导入数据后进入，进入下载页面会闪退

### ISSUE THREAD

**Issue by dairidong** [EhViewer-NekoInverter/EhViewer#22]
### 复现步骤 / Step to reproduce

1.通过其他分支导出数据（彩e和转换格式后的绿e都试过）
2.安装本分支下的最新版本
3.导入db文件，然后进入下载列表，直接闪退

### 预期行为 / Expected behaviour

正常进入

### 实际行为 / Actual Behaviour

秒闪退

### EhViewer 版本号 / EhViewer version code

1.7.28

### EhViewer CI 版本 / EhViewer CI Version

非开发人员，不了解

### Android 系统版本 / Android version

ColorOS 13.0 / Android 13

### 设备型号 / Device model

Oppo Find X3

### SoC 型号 / Soc model

骁龙870

### 应用日志 / App logs

--------- beginning of crash
01-08 16:02:26.259  9410  9410 E AndroidRuntime: FATAL EXCEPTION: main
01-08 16:02:26.259  9410  9410 E AndroidRuntime: Process: org.moedog.ehviewer, PID: 9410
01-08 16:02:26.259  9410  9410 E AndroidRuntime: java.lang.IllegalArgumentException: Comparison method violates its general contract!
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at java.util.TimSort.mergeHi(TimSort.java:903)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at java.util.TimSort.mergeAt(TimSort.java:520)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at java.util.TimSort.mergeForceCollapse(TimSort.java:461)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at java.util.TimSort.sort(TimSort.java:254)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at java.util.Arrays.sort(Arrays.java:1427)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at java.util.List.sort(List.java:525)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at java.util.Collections.sort(Collections.java:206)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at oi.r1(Unknown Source:120)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at oi.h0(Unknown Source:40)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at androidx.fragment.app.a.e(Unknown Source:68)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at androidx.fragment.app.a.k(Unknown Source:158)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at hr.z(Unknown Source:1063)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at hr.U(Unknown Source:81)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at hr.x(Unknown Source:73)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at TQ.run(Unknown Source:53)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:240)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:351)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8321)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
01-08 16:02:26.259  9410  9410 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1012)

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by dairidong** [comment]
fixed in [v1.7.29.1](https://github.com/EhViewer-NekoInverter/EhViewer/releases/tag/v1.7.29.1)
